server:
  port: ${SERVER_PORT:8006}
  shutdown: graceful

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: billing-service
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: ${KAFKA_GROUP:billing-service}
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "com.sa.healntrack.*"
    producer:
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    listener:
      concurrency: ${KAFKA_CONCURRENCY:3}
      ack-mode: record

billing:
  topic:
    requested: ${TOPIC_BILLING_REQUESTED:billing.requested}
  template:
    default-key: ${BILLING_TEMPLATE_KEY:invoice/default}

topics:
  notification:
    requested: ${TOPIC_NOTIFICATION_REQUESTED:notification.requested}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:info}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_HIBERNATE_BIND:info}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/
